# Exported from Render on 2026-06-21T20:39:51Z
version: "1"
projects:
- name: infoLinks
  environments:
  - name: Production
    services:
    - type: web
      name: Info_Links Main Branch
      runtime: docker
      repo: https://github.com/MohamadObeid9/Info_Links
      plan: free
      envVars:
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: METRICS_BASIC_AUTH_PASSWORD
        sync: false
      - key: METRICS_BASIC_AUTH_USER
        sync: false
      - key: APP_ENV
        sync: false
      - key: SITE_BASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      region: oregon
      dockerfilePath: ./Dockerfile
      healthCheckPath: /readyz
      domains:
      - www.infolinks.app
      - infolinks.app
      autoDeployTrigger: checksPass
